const mongoose = require('mongoose')

const creditSchema = new mongoose.Schema({
    fname:{
        type:String,
        required:true,
        trim:true
    },
    mname:{
        type:String,
    },
    lname:{
        type:String,
        required:true,
        trim:true
    },
    phone:{
        type:Number,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        trim:true
    },
    streetNo:{
        type:String,
        required:true,
        trim:true
    },
    streetName:{
        type:String,
        required:true,
    },
    Apartment:{
        type:String,
        trim:true
    },
    zipCode:{
        type:Number,
        required:true,
        trim:true
    },
    city:{
        type:String,
        required:true,
        trim:true
    },
    state:{
        type:String,
        required:true,
        trim:true
    },
    housingStatus:{
        type:String,
        required:true,
        trim:true
    },
    timeAtAddress:{
        type:Number,
        required:true,
        trim:true
    },
    mortgage:{
        type:Number,
        required:true,
        trim:true
    },
    SSN:{
        type:String,
        required:true,
        trim:true
    },
    employmentStatus:{
        type:String,
        required:true,
        trim:true
    },
    incomeSrc:{
        type:String,
    },
    income:{
        type:String,
        required: true,
        trim:true
    },
    incomeSrc2:{
        type:String,
    },
    income2:{
        type:String,
        trim:true
    }

},{timestamps:true})

module.exports = mongoose.model("credit", creditSchema);
