export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const categoryConstants = {
  GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
  GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
  GET_ALL_CATEGORIES_FAILED: 'GET_ALL_CATEGORIES_FAILED',
  CREATE_NEW_CATEGORIES_REQUEST: 'CREATE_NEW_CATEGORIES_REQUEST',
  CREATE_NEW_CATEGORIES_SUCCESS: 'CREATE_NEW_CATEGORIES_SUCCESS',
  CREATE_NEW_CATEGORIES_FAILED: 'CREATE_NEW_CATEGORIES_FAILED',
  UPDATE_CATEGORIES_REQUEST: 'UPDATE_CATEGORIES_REQUEST',
  UPDATE_CATEGORIES_SUCCESS: 'UPDATE_CATEGORIES_SUCCESS',
  UPDATE_CATEGORIES_FAILURE: 'UPDATE_CATEGORIES_FAILURE',
  DELETE_CATEGORIES_REQUEST: 'DELETE_CATEGORIES_REQUEST',
  DELETE_CATEGORIES_SUCCESS: 'DELETE_CATEGORIES_SUCCESS',
  DELETE_CATEGORIES_FAILURE: 'DELETE_CATEGORIES_FAILURE',
}
